version: '3.4'

services:
  bugtrackerapi:
    image: bugtrackerapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: ${PORT}
      CLIENT_URL: ${CLIENT_URL}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      AXIOM_DATASET: ${AXIOM_DATASET}
      AXIOM_TOKEN: ${AXIOM_TOKEN}
      NODE_ENV: production
    ports:
      - ${PORT}:${PORT}
