version: '3.4'

services:
  bugtrackerapi:
    image: bugtrackerapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
